# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3800a40bd55b1b472cc1a811d70e5ab7de6752e82bfa534d7101e9575e3211f396eeb35bad02a5eebcc7f9041bf94d40509a2b006be2dd781c130428bac5bef2

test:
  secret_key_base: ad8dbccc4178dd42c9be19933ac710d8c2db4c0accf45c42faa9c23256a9b1ba7423c7030238aeccf9e8c8508274b6cd60dca47754fb0cc004cb73c07398a62b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
